layout_spectrum: 0.7416756
color:
  saturation: 0.17884
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#E9EAE9'
    - '#C4BDB4'
    - '#918877'
    - '#5C5B53'
    - '#393831'
  rhythmicContrast: 0.1960257
typography_spectrum: 0.6858217
name: Annie Axelrod
